---
title: "class 5 help"
author: "Erica Birkholz"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Class 5 Graphics and Plots

#'This is some narrative text that I can style **bold** or *italic* and add links
#'[webpages](https://rmarkdown.rstudio.com/articles_report_from_r_script.html)

#Section 2A: line plot

weight <- read.table("bimm143_05_rstats/weight_chart.txt", header = TRUE)
plot(weight, pch=15, cex=1.5, lwd=2, ylim=c(2,10), xlab="Age (months)", ylab="Weight (kg)", main="Baby Weight")
plot(weight, typ="o", pch=15, cex=1.5, lwd=2, ylim=c(2,10), col="magenta", xlab="Age (months)", ylab="Weight (kg)", main="Baby Weight")

#Section 2B: Barplot

feat <- read.table("bimm143_05_rstats/feature_counts.txt", header=T, sep="\t")
par(mar=c(3, 11, 4, 2))
barplot(feat$Count, horiz=T, ylab="Features", names.arg = feat$Feature, main="Mouse Features", las=1, xlim=c(0,80000))

#Section 2C: Histograms

tenthou <- c(rnorm(10000), rnorm(10000)+4)
par(mar=c(3, 5, 4, 2))
hist(tenthou, breaks=30)

#Section 3A: Color
mf <- read.table("bimm143_05_rstats/male_female_counts.txt", header=T, sep="\t")
par(mar=c(6, 4, 4, 2))
barplot(mf$Count, col=c("blue2", "red2"), main="Male and Female", ylim=c(0,20), names.arg=mf$Sample, las=2)        

#Section 3B: Color by Value

genes <- read.table("bimm143_05_rstats/up_down_expression.txt", header=T, sep="\t")
table(genes$State)
palette(c("magenta", "cyan", "yellow"))
par(mar=c(5, 5, 4, 2))
plot(genes$Condition1, genes$Condition2, col=genes$State, xlab="Condition 1", ylab="Condition 2", main="Gene Expression")
